apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot-k3s
servers: 1
agents: 2
ports:
  - port: 8008:8008
    nodeFilters:
      - loadbalancer
# k3d cluster create -p "8081:80@loadbalancer" --agents 2 --name iot-k3s